image: 
  file: docker.yml
  
tasks:
  - name: Docker Compose
    command: docker-compose -f docker.yaml

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
    - Snakemake.snakemake-lang
